#' Simulate a network
#'
#' Simulate a network based on the formulation of a latent position model with
#' multiplicative truncated gamma process incorporated
#'
#'
#' @param n Number of observations/nodes in the network
#' @param d Number of latent dimensions (truncation level)
#' @param alpha A number specifying the overall connection level in the network
#' @param seed Specify how the random number generator should be initialized
#' @param deltas A numeric vector specifying the shrinkage strength of the
#' dimensions
#' @param dim1 A numeric vector of length 2 specifying the shape and rate
#' parameters of the gamma distribution for the first dimension
#' @param dim2 A numeric vector of length 2 specifying the shape and rate
#' parameters of the truncated gamma distribution for the second and higher
#' dimensions
#' @param type The network type with edges being binary valued or count valued
#' @param symmetric Create a undirected/directed network when it is set as
#' TRUE/FALSE respectively
#'
#' @details
#' The simulated data were generated by Bernoulli trials for each node pairs in
#' the adjacency matrix based on the probabilities derived from the distances
#' between the nodes' latent positions. A logistic regression model is used to
#' model the probability of forming an edge between two nodes as a function of
#' the Euclidean distance and alpha. The latent positions are sampled from a
#' multivariate normal distribution where the mean vector is zero while the
#' diagonal covariance matrix has variances that comes from the inverse
#' cumulative product of the shrinkage strengths of the latent dimensions. The
#' shrinkage strengths comes from the truncated gamma distribution, or may be
#' manually set.
#'
#' @return A list containing the simulated network and its parameters
#' \item{network}{The \eqn{n x n} adjacency matrix of the simulated network}
#' \item{alpha}{The true overall connection level used to simulate the network}
#' \item{positions}{The true latent positions of the network}
#' \item{prob}{The probability matrix used to simulate the network}
#' \item{variances}{The true variances used to simulate the latent positions}
#' \item{omegas}{The true precision}
#' \item{deltas}{The true shrinkage strength}
#' \item{seed}{The seed used to initialise the algorithm}
#'
#' @export
#'
#' @importFrom stats dist rbinom rgamma rnorm rpois
#' @importFrom truncdist rtrunc
#' @importFrom mvtnorm rmvnorm
#'
#' @family functions
#'
#' @examples
#' # Simulate binary network by sampling shrinkage strengths from distribution
#' sampleMTGP_2D <- networkMTGP(n = 50, d = 2, alpha = 3,
#' type = "binary") # 2D latent positions
#' sampleMTGP_4D <- networkMTGP(n = 50, d = 4, alpha = 3,
#' type = "binary") # 4D latent positions
#'
#' # Simulate binary network by directly specifying shrinkage strengths
#' sampleMTGP <- networkMTGP(n = 50, alpha = 3,
#' deltas = c(0.5,1.1), type = "binary") # 2D positions
#'
#' # Simulate count network by directly specifying shrinkage strengths
#' sampleMTGP_count <- networkMTGP(n = 50, alpha = 3,
#' deltas = c(0.5,1.1), type = "count") # 2D positions
#'
networkMTGP <- function(n, d, alpha, seed, deltas, type =c("binary", "count"),
                       symmetric = FALSE, dim1 = c(1.1, 1), dim2 = c(2, 1)) {
  edgetype <- match.arg(type)
  if (!missing(seed)) {
    set.seed(seed) # set seed if exists
  } else {
    seed <- sample(1:1e5, 1) # sample a seed from 1 to 10,000
  }


  # If deltas are not specified, sample from (truncated) gamma distribution
  if (missing(deltas)) {
    deltas <- rgamma(1, shape = dim1[1], rate = dim1[2]) # First dimension delta
    deltas <- c(deltas, rtrunc(
      n = (d - 1), spec = "gamma",
      shape = dim2[1], rate = dim2[2], a = 1 # a is truncated point
    ))
  } else if (is.vector(deltas, mode = "numeric")) {
    deltas <- deltas
  } else {
    print("Error in Shrinkage Strength (delta)")
  }

  omegas <- cumprod(deltas) # Calculate Precision
  variances <- 1 / omegas # Calculate Variance

  # Sample latent positions
  if (length(variances) == 1) {
    z <- rnorm(n, sd = sqrt(variances)) # 1D positions data
  } else {
    z <- rmvnorm(n, sigma = diag(variances)) # 2D and more positions data
  }

  # Distance matrix with Squared Euclidean distance
  dist_btwn_z <- dist(z, diag = TRUE, upper = TRUE, method = "euclidean")^2

  if(edgetype == "binary") {
    logit_p_numerator <- exp(alpha - dist_btwn_z)
    p <- as.matrix(logit_p_numerator / (1 + logit_p_numerator)) # prob. matrix
    y0 <- matrix(rbinom(p, 1, p), nrow = n, ncol = n)
  } else if(edgetype == "count") {

    p <- as.matrix(exp(alpha - dist_btwn_z))     # Calculate rate matrix
    y0 <- matrix(rpois(p, p), nrow = n, ncol = n)

  }

  # Adjacency matrix, i.e. the network data
  if(symmetric) {
    y0[lower.tri(y0)]<-t(y0)[lower.tri(y0)]
    y <- y0
  } else {
    y <- y0
  }


  results <- list(
    network = y,
    alpha = alpha,
    positions = z,
    prob = p,
    variances = variances,
    omegas = omegas,
    deltas = deltas,
    seed = seed,
    symmetric = symmetric
  )

  invisible(results)
}
