#' Simulate a LSPCM based network
#'
#' Simulate a network based on the formulation of a latent shrinkage position
#' cluster model (LSPCM) with the multiplicative truncated gamma process
#' incorporated
#'
#'
#' @param n Number of observations/nodes in the network
#' @param alpha A number specifying the overall connection level in the network
#' @param seed Specify how the random number generator should be initialized
#' @param deltas A numeric vector specifying the shrinkage strength of the
#' dimensions
#' @param dim1 A numeric vector of length 2 specifying the shape and rate
#' parameters of the gamma distribution for the first dimension
#' @param dim2 A numeric vector of length 2 specifying the shape and rate
#' parameters of the truncated gamma distribution for the second and higher
#' dimensions
#' @param symmetric Create a undirected/directed network when it is set as
#' TRUE/FALSE respectively
#' @param n_dimen The number of dimension simulated for the latent position
#' @param G The number of clusters
#' @param mix_prop A numeric vector specifying the mixing proportion
#' @param mix_prior A numberic vector specifying the hyperparameter for the
#' mixing prior
#' @param cluster_mean A \eqn{G x p} matrix specifying the cluster means
#' @param same_delta_G A binary statement indicating if the same shrinkage
#' strength is used across clusters
#'
#' @details
#' The simulated data were generated by Bernoulli trials for each node pairs in
#' the adjacency matrix based on the probabilities derived from the distances
#' between the nodes' latent positions. A logistic regression model is used to
#' model the probability of forming an edge between two nodes as a function of
#' the Euclidean distance and alpha. The latent positions are sampled from a
#' multivariate normal distribution where the mean follows a multivariate normal
#' hyperprior while the diagonal covariance matrix has variances that comes from
#' the inverse cumulative product of the shrinkage strengths of the latent
#' dimensions. The shrinkage strengths comes from the truncated gamma
#' distribution, or may be manually set.
#'
#' @return A list containing the simulated network and its parameters
#' \item{network}{The \eqn{n x n} adjacency matrix of the simulated network}
#' \item{alpha}{The true overall connection level used to simulate the network}
#' \item{positions}{The true latent positions of the network}
#' \item{cluster_mean}{The central position of the clusters}
#' \item{mix_prop}{The mixing proportion of the latent positions}
#' \item{cluster}{The cluster labels for the nodes in the network}
#' \item{prob}{The probability matrix used to simulate the network}
#' \item{variances}{The true variances used to simulate the latent positions}
#' \item{omegas}{The true precision}
#' \item{deltas}{The true shrinkage strength}
#' \item{seed}{The seed used to initialise the algorithm}
#' \item{symmetric}{A TRUE/FALSE statement indicating if the network is
#' undirected/directed}
#'
#' @export
#'
#' @importFrom stats dist rbinom rgamma rnorm rpois
#' @importFrom truncdist rtrunc
#' @importFrom mvtnorm rmvnorm
#' @importFrom MCMCpack rdirichlet
#'
#' @family functions
#'
#' @examples
#' # Simulate binary network from positions of 2 dimensions and 3 clusters
#' sampleLSPCM_2D <- networkMTGP_cluster(n = 50, n_dimen = 2, G = 3, alpha = 7,
#' cluster_mean = matrix(c(0,0, -5,0, -5,5), ncol = 2, byrow = TRUE), seed = 1,
#' deltas = matrix(rep(c(.5,1.05), 3), nrow = 3, byrow = TRUE))
#'
networkMTGP_cluster <- function(n, n_dimen, G, alpha, seed, symmetric = FALSE,
                                mix_prop, mix_prior = rep(10, G),
                                cluster_mean = matrix(0, nrow=G, ncol=n_dimen),
                                deltas, dim1 = matrix(c(2,1), nrow=G, ncol=n_dimen, byrow = TRUE), same_delta_G = TRUE,
                                dim2 = matrix(c(3,1), nrow=G, ncol=n_dimen, byrow = TRUE)) {

  if (!missing(seed)) {
    set.seed(seed) # set seed if exists
  } else {
    seed <- sample(1:1e5, 1) # sample a seed from 1 to 10,000
  }


  if(G==1){
    # If deltas are not specified, sample from (truncated) gamma distribution
    if (missing(deltas)) {
      deltas <- rgamma(1, shape = dim1[1,1], rate = dim1[1,2]) # First dimension delta
      if(n_dimen>1) {
        deltas <- c(deltas, rtrunc(
          n = (n_dimen - 1), spec = "gamma",
          shape = dim2[1,1], rate = dim2[1,2], a = 1 # a is truncated point
        ))
      }
    } else if (is.matrix(deltas)) {
      deltas <- deltas
    } else {
      stop("Error in Shrinkage Strength (delta)")
    }

    omegas <- cumprod(deltas) # Calculate Precision
    variances <- 1 / omegas # Calculate Variance

    # Sample latent positions
    if (length(variances) == 1) {
      z <- rnorm(n, sd = sqrt(variances)) # 1D positions data
    } else {
      z <- mvtnorm::rmvnorm(n, sigma = diag(variances)) # 2D and more positions data
    }

    mix_prop <- cluster_indicator <- NULL

  } else  if(G>1) {
    # If deltas are not specified, sample from (truncated) gamma distribution
    if (missing(deltas)) {
      if(!is.matrix(dim1)) {
        stop("Please make sure prior dim1 is initialised with a matrix")
      }
      if(!is.matrix(dim2)) {
        stop("Please make sure prior dim2 is initialised with a matrix")
      }
      deltas <- matrix(Inf, nrow=G, ncol=n_dimen) # initialise matrix with length G and n_dimen elements each
      for(i in 1:G) {
        if(same_delta_G){

          delta1<- rgamma(1, shape = dim1[1,1], rate = dim1[1,2])
          delta2  <- rtrunc(
            n = (n_dimen - 1), spec = "gamma",
            shape = dim2[1,1], rate = dim2[1,2], a = 1 # a is truncated point
          )
          # deltas[i,1]  <- delta1
          # deltas[i,2:n_dimen]  <- delta2
          deltas = matrix(rep(c(delta1, delta2), G), nrow=G, ncol=n_dimen, byrow=TRUE)
          break()

        } else {
          deltas[i,1] <- rgamma(1, shape = dim1[i,1], rate = dim1[i,2])
          deltas[i,2:n_dimen]  <- rtrunc(
            n = (n_dimen - 1), spec = "gamma",
            shape = dim2[i,1], rate = dim2[i,2], a = 1 # a is truncated point
          )
        }
      }
    } else if (is.matrix(deltas)) {
      deltas <- deltas
    } else {
      stop("Please input deltas as matrix!")
    }
    omegas <- t(apply(deltas, 1, cumprod)) # Calculate Precision
    variances <- 1/omegas # Calculate Variance

    if (missing(mix_prop)) {
      mix_prop <- rdirichlet(1,mix_prior)
    } else if(length(mix_prop) == G) {
      mix_prop <- mix_prop/sum(mix_prop)
    } else {
      stop("Please input proper vector of mix_prop or mix_prior")
    }

    cluster_indicator <- sample(1:G, size = n, replace = TRUE, prob = mix_prop)

    if (missing(cluster_mean)) {
      for(i in 1:G){
        # browser()
        cluster_mean[i,] <- mvtnorm::rmvnorm(1, sigma=(diag(variances[i,]) ))
      }

    } else if(is.matrix(cluster_mean)){
      cluster_mean = cluster_mean
    } else {
      stop("Please input proper cluster_mean or cluster_mean_prior")
    }
    z <- c()
    for(i in cluster_indicator) {
      # Sample latent positions
      if (length(variances[i,]) == 1) {
        z <- rbind(z, matrix(rnorm(1, mean = cluster_mean[i,], sd = sqrt(variances[i,])))) # 1D positions data
      } else {
        z <- rbind(z, mvtnorm::rmvnorm(1, mean = cluster_mean[i,], sigma = diag(variances[i,]))) # 2D and more positions data
      }
    }


  } else {
    stop("Cluster size, G, has to be larger than 0")
  }

  z[is.na(z)] = 0



  # Distance matrix with Squared Euclidean distance
  dist_btwn_z <- dist(z, diag = TRUE, upper = TRUE, method = "euclidean")^2

  # Calculate probabilities matrix
  logit_p_numerator <- exp(alpha - dist_btwn_z)
  p <- as.matrix(logit_p_numerator / (1 + logit_p_numerator))

  if(G==1){
    y0 <- matrix(rbinom(p, 1, p), nrow = n, ncol = n)
  } else if(G>1) {
    y0 <- matrix(rbinom(p, 1, p), nrow = sum(n), ncol = sum(n))
  }


  # Adjacency matrix, i.e. the network data
  if(symmetric) {
    y0[lower.tri(y0)]<-t(y0)[lower.tri(y0)]
    y <- y0
  } else {
    y <- y0
  }


  results <- list(
    network = y,
    alpha = alpha,
    positions = z,
    cluster_mean = cluster_mean,
    mix_prop = mix_prop,
    cluster = cluster_indicator,
    prob = p,
    variances = variances,
    omegas = omegas,
    deltas = deltas,
    seed = seed,
    symmetric = symmetric
  )

  invisible(results)
}
